import 'data_source_info.dart';

/// Distinguishes the origin of each value in a recommendation.
///
/// The UI MUST render these differently so the user understands what
/// is measured data, what is calculated, and what is AI-generated text.
enum RecommendationValueType {
  /// Value was directly measured from a health sensor or device.
  measured,

  /// Value was deterministically calculated from verified data.
  calculated,

  /// Value is a general wellness guideline (not personalized).
  generalGuideline,

  /// Text was generated by the AI model to explain verified facts.
  aiExplanation,

  /// A safety warning — may require professional consultation.
  safetyWarning,
}

/// A single value within a recommendation, with its type and source.
class RecommendationValue {
  const RecommendationValue({
    required this.label,
    required this.value,
    required this.type,
    required this.source,
    this.unit,
    this.safetyNote,
  });

  /// Human-readable label for this value (e.g. "Total Calories").
  final String label;

  /// The value as a display string (e.g. "450", "High Risk").
  final String value;

  /// Whether this was measured, calculated, or AI-generated.
  final RecommendationValueType type;

  /// Provenance of this value.
  final DataSourceInfo source;

  /// Optional unit (e.g. "kcal", "mg/dL", "bpm").
  final String? unit;

  /// Safety note to display alongside critical or high-risk values.
  final String? safetyNote;

  bool get isSafetyWarning => type == RecommendationValueType.safetyWarning;
  bool get isAiGenerated => type == RecommendationValueType.aiExplanation;

  String get typeLabel => switch (type) {
        RecommendationValueType.measured => 'Measured',
        RecommendationValueType.calculated => 'Calculated',
        RecommendationValueType.generalGuideline => 'General Guideline',
        RecommendationValueType.aiExplanation => 'AI Explanation',
        RecommendationValueType.safetyWarning => 'Safety Notice',
      };
}

/// A fully assembled, AI-ready recommendation with type-safe provenance.
///
/// This is what the [RecommendationSafetyLayer] produces and what the
/// AI receives as structured context. The AI explanation text is added
/// AFTER the recommendation context is validated — it is stored in
/// [aiExplanation] after the AI call.
///
/// ── Rendering contract ────────────────────────────────────────────────────────
/// The UI must:
///   1. Show [safetyWarnings] first, with a distinct warning colour.
///   2. Show [measuredValues] and [calculatedValues] with source attribution.
///   3. Show [aiExplanation] clearly labelled "AI Explanation".
///   4. Never show [aiExplanation] values as facts — always as interpretation.
///   5. Show [disclaimer] always, regardless of recommendation level.
class TrustedRecommendation {
  const TrustedRecommendation({
    required this.id,
    required this.title,
    required this.values,
    required this.safetyWarnings,
    required this.disclaimer,
    required this.generatedAt,
    required this.overallSource,
    this.aiExplanation,
    this.requiresProfessionalConsultation = false,
  });

  /// Unique ID for this recommendation (for logging/analytics).
  final String id;

  /// Short title describing what this recommendation covers.
  final String title;

  /// All values included in this recommendation, with type labels.
  final List<RecommendationValue> values;

  /// Safety warnings that must be prominently displayed.
  final List<String> safetyWarnings;

  /// Always-visible disclaimer about AI and health decisions.
  final String disclaimer;

  /// When this recommendation was generated.
  final DateTime generatedAt;

  /// The lowest-confidence data source used across all values.
  final DataSourceInfo overallSource;

  /// AI-generated explanation of the verified facts.
  /// Null until the AI call completes.
  final String? aiExplanation;

  /// Whether this recommendation requires seeing a healthcare professional.
  final bool requiresProfessionalConsultation;

  // ── Derived ────────────────────────────────────────────────────────────────

  List<RecommendationValue> get measuredValues =>
      values.where((v) => v.type == RecommendationValueType.measured).toList();

  List<RecommendationValue> get calculatedValues => values
      .where((v) => v.type == RecommendationValueType.calculated)
      .toList();

  List<RecommendationValue> get guidelineValues => values
      .where((v) => v.type == RecommendationValueType.generalGuideline)
      .toList();

  bool get hasAiExplanation => aiExplanation != null;
  bool get hasSafetyWarnings => safetyWarnings.isNotEmpty;

  /// Minimum confidence across all included values.
  double get minimumConfidence => values.isEmpty
      ? 0.0
      : values
          .map((v) => v.source.confidenceScore)
          .reduce((a, b) => a < b ? a : b);

  /// Creates a copy with an AI explanation attached.
  TrustedRecommendation withAiExplanation(String explanation) =>
      TrustedRecommendation(
        id: id,
        title: title,
        values: values,
        safetyWarnings: safetyWarnings,
        disclaimer: disclaimer,
        generatedAt: generatedAt,
        overallSource: overallSource,
        aiExplanation: explanation,
        requiresProfessionalConsultation: requiresProfessionalConsultation,
      );

  // ── Standard disclaimers ───────────────────────────────────────────────────

  static const String kNutritionDisclaimer =
      'Nutrition values are based on general food database averages. '
      'Actual values may vary by preparation method, brand, and portion. '
      'This is not a substitute for professional nutritional advice.';

  static const String kHealthDisclaimer =
      'Health metric classifications are based on general clinical guidelines. '
      'Individual results may vary. Always consult a qualified healthcare '
      'provider before making health decisions.';

  static const String kAiDisclaimer =
      'AI explanations interpret verified data but may not reflect your '
      'individual medical situation. This app does not diagnose conditions '
      'or replace professional medical advice.';

  @override
  String toString() =>
      'TrustedRecommendation('
      'title=$title, '
      'values=${values.length}, '
      'warnings=${safetyWarnings.length}, '
      'hasAi=$hasAiExplanation)';
}
